services:
  influxdb2:
    image: influxdb:2
    container_name: trevcan-influxdb
    restart: unless-stopped
    ports:
      - '127.0.0.1:8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USERNAME:?set INFLUXDB_ADMIN_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:?set INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN:?set INFLUXDB_TOKEN}
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2

  grafana:
    image: grafana/grafana-enterprise
    container_name: trevcan-grafana
    restart: unless-stopped
    depends_on:
      - influxdb2
    ports:
      - '${GRAFANA_BIND_ADDRESS:-0.0.0.0}:3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USERNAME:?set GRAFANA_ADMIN_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:?set GRAFANA_ADMIN_PASSWORD}
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 1s
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN:?set INFLUXDB_TOKEN}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./telemetry/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./telemetry/grafana/generated:/var/lib/grafana/dashboards:ro

volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-data:
