apiVersion: 1

datasources:
  - name: TREVCAN InfluxDB
    uid: trevcan-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb2:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: docs
      defaultBucket: home
      httpMode: POST
    secureJsonData:
      token: $INFLUXDB_TOKEN

